### ISSUE TITLE
[Feature request]: Rotated Pride flags

### ISSUE THREAD

**Issue by JustAnotherJavaProgrammer** [YorikHansen/better-moodle#13]
### Geht deine Idee aus einer Problemstellung hervor? / Is your feature related to a problem?

Currently, only the rainbow flag is available in a rotated (45°) version

All the other pride flags are perfectly straight

### Lösung oder Feature / Solution or Feature

Add rotated versions of the other pride flags

**Comment by YorikHansen** [comment]
This is resolved in [v1.39.0](https://github.com/YorikHansen/better-moodle/releases/tag/1.39.0)
