### ISSUE TITLE
Agender flag broken

### ISSUE THREAD

**Issue by JustAnotherJavaProgrammer** [YorikHansen/better-moodle#20]
### Was ist passiert / What happened?

When I set the Agender flag to be displayed in the logo, the rainbow flag is displayed instead.

### Wie kann man den Fehler reproduzieren? / How to reproduce?

1. Open the settings
2. Choose flag "Agender"
3. Save
4. Rainbow flag is displayed instead

### Erwartetes Verhalten / Expected behavior

I would expect to see the agender flag in the moodle logo.

### System

- Firefox for Android 128.0.1 (Build #2016032759)
- Better-Moodle 1.39.0

**Comment by YorikHansen** [comment]
Resolved in [v1.39.1](https://github.com/YorikHansen/better-moodle/releases/tag/1.39.1)
